// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkhnmzuduikmpwuqyohv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndraG5tenVkdWlrbXB3dXF5b2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjIxMzQsImV4cCI6MjA2NDIzODEzNH0.z1Y1yQhJy8TKoM5UxqrmyXk4Zz-yI-u107uvHFGHaXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);